export const player_prop_markets = [
    { 
      player_markets: "player_pass_tds,player_pass_yds,player_pass_completions,player_pass_attempts,player_pass_interceptions,player_pass_longest_completion,player_rush_yds,player_rush_attempts,player_rush_longest,player_receptions,player_reception_yds,player_reception_longest,player_kicking_points,player_field_goals,player_tackles_assists,player_1st_td,player_last_td,player_anytime_td",
      team_markets:"alternate_spreads,alternate_totals,h2h_q1,h2h_q2,h2h_q3,h2h_q4,h2h_h1,h2h_h2,spreads_q1,spreads_q2,spreads_q3,spreads_q4,spreads_h1,spreads_h2,totals_q1,totals_q2,totals_q3,totals_q4,totals_h1,totals_h2,",
      label: "americanfootball_nfl"
    },
    { 
      player_markets: "",
      team_markets:"alternate_spreads,alternate_totals,h2h_q1,h2h_q2,h2h_q3,h2h_q4,h2h_h1,h2h_h2,spreads_q1,spreads_q2,spreads_q3,spreads_q4,spreads_h1,spreads_h2,totals_q1,totals_q2,totals_q3,totals_q4,totals_h1,totals_h2",
      label: "americanfootball_ncaaf"
    },
    {
      player_markets: "player_points,player_rebounds,player_assists,player_threes,player_blocks,player_steals,player_turnovers,player_points_rebounds_assists,player_points_rebounds,player_points_assists,player_rebounds_assists,player_double_double,player_first_basket,player_triple_double",
      team_markets: "alternate_spreads,alternate_totals,h2h_q1,h2h_q2,h2h_q3,h2h_q4,h2h_h1,h2h_h2,spreads_q1,spreads_q2,spreads_q3,spreads_q4,spreads_h1,spreads_h2,totals_q1,totals_q2,totals_q3,totals_q4,totals_h1,totals_h2,",
      label: "basketball_nba"
    },
	{
		player_markets: "player_points,player_rebounds,player_assists,player_threes,player_blocks,player_steals,player_turnovers,player_points_rebounds_assists,player_points_rebounds,player_points_assists,player_rebounds_assists,player_double_double,player_first_basket,player_triple_double",
		team_markets: "alternate_spreads,alternate_totals,h2h_q1,h2h_q2,h2h_q3,h2h_q4,h2h_h1,h2h_h2,spreads_q1,spreads_q2,spreads_q3,spreads_q4,spreads_h1,spreads_h2,totals_q1,totals_q2,totals_q3,totals_q4,totals_h1,totals_h2,",
		label: "basketball_wnba"
	},
    {
      player_markets: "",
      team_markets: "alternate_spreads,alternate_totals,h2h_h1,h2h_h2,spreads_h1,spreads_h2,totals_h1,totals_h2",
      label: "basketball_ncaab"
    },
    {
      player_markets: "batter_home_runs,batter_first_home_run,batter_hits,batter_total_bases,batter_rbis,batter_runs_scored,batter_hits_runs_rbis,batter_singles,batter_doubles,batter_triples,batter_walks,batter_strikeouts,batter_stolen_bases,pitcher_strikeouts,pitcher_record_a_win,pitcher_hits_allowed,pitcher_walks,pitcher_earned_runs,pitcher_outs,batter_total_bases_alternate,batter_home_runs_alternate,batter_hits_alternate,batter_rbis_alternate,pitcher_hits_allowed_alternate,pitcher_walks_alternate,pitcher_strikeouts_alternate",
      team_markets: "alternate_spreads,alternate_totals,h2h_1st_1_innings,h2h_1st_3_innings,h2h_1st_5_innings,h2h_1st_7_innings,spreads_1st_1_innings,spreads_1st_3_innings,spreads_1st_5_innings,spreads_1st_7_innings,totals_1st_1_innings,totals_1st_3_innings,totals_1st_5_innings,totals_1st_7_innings,",
      label: "baseball_mlb"
    },
    {
      player_markets: "player_points,player_power_play_points,player_assists,player_blocked_shots,player_shots_on_goal,player_total_saves,player_goal_scorer_first,player_goal_scorer_last,player_goal_scorer_anytime,player_goals,player_points_alternate,player_assists_alternate,player_power_play_points_alternate,player_goals_alternate,player_shots_on_goal_alternate,player_blocked_shots_alternate,player_total_saves_alternate",
      team_markets: "alternate_spreads,alternate_totals,h2h_p1,h2h_p2,h2h_p3,spreads_p1,spreads_p2,spreads_p3,totals_p1,totals_p2,totals_p3,",
      label: "icehockey_nhl"
    }
]

export const additional_team_props = new Set(["alternate_spreads","alternate_totals","h2h_q1","h2h_q2","h2h_q3","h2h_q4","h2h_h1","h2h_h2","spreads_q1","spreads_q2","spreads_q3","spreads_q4","spreads_h1","spreads_h2","totals_q1","totals_q2","totals_q3","totals_q4","totals_h1","totals_h2","h2h_1st_1_innings","h2h_1st_3_innings","h2h_1st_5_innings","h2h_1st_7_innings","spreads_1st_1_innings","spreads_1st_3_innings","spreads_1st_5_innings","spreads_1st_7_innings","totals_1st_1_innings","totals_1st_3_innings","totals_1st_5_innings","totals_1st_7_innings",
                                              "h2h_p1","h2h_p2","h2h_p3","spreads_p1","spreads_p2","spreads_p3","totals_p1","totals_p2","totals_p3"]);
export const all_player_props = new Set(["player_pass_tds","player_pass_yds","player_pass_completions","player_pass_attempts","player_pass_interceptions","player_pass_longest_completion","player_rush_yds","player_rush_attempts","player_rush_longest","player_receptions","player_reception_yds","player_reception_longest","player_kicking_points","player_field_goals","player_tackles_assists","player_1st_td","player_last_td","player_anytime_td","player_points","player_rebounds","player_assists","player_threes",
                                          "player_blocks","player_steals","player_turnovers","player_points_rebounds_assists","player_points_rebounds","player_points_assists","player_rebounds_assists","player_double_double","player_triple_double","player_first_basket","batter_home_runs","batter_first_home_run","batter_hits","batter_total_bases","batter_rbis","batter_runs_scored","batter_hits_runs_rbis","batter_singles","batter_doubles","batter_triples","batter_walks","batter_strikeouts","batter_stolen_bases","pitcher_strikeouts",
										  "batter_total_bases_alternate","batter_home_runs_alternate","batter_hits_alternate","batter_rbis_alternate","pitcher_hits_allowed_alternate","pitcher_walks_alternate","pitcher_strikeouts_alternate",
                                          "pitcher_record_a_win","pitcher_hits_allowed","pitcher_walks","pitcher_earned_runs","pitcher_outs","player_power_play_points","player_blocked_shots","player_shots_on_goal","player_total_saves","player_goal_scorer_first","player_goal_scorer_last","player_goal_scorer_anytime", "player_goals","player_points_alternate","player_assists_alternate","player_power_play_points_alternate","player_goals_alternate","player_shots_on_goal_alternate","player_blocked_shots_alternate","player_total_saves_alternate"])

export const league_titles = {
  "americanfootball_nfl":"NFL",
  "americanfootball_ncaaf":"NCAAF",
  "basketball_nba":"NBA",
  "basketball_ncaab":"NCAAB",
  "basketball_wnba":"WNBA",
  "baseball_mlb":"MLB",
  "icehockey_nhl":"NHL",
}

export const player_prop_choices = {
  //football
  "player_pass_tds":"Pass Touchdowns",
  "player_pass_yds":"Pass Yards",
  "player_pass_completions":"Pass Completions",
  "player_pass_attempts":"Pass Attempts",
  "player_pass_interceptions":"Pass Interceptions",
  "player_pass_longest_completion":"Pass Longest Completion",
  "player_rush_yds":"Rush Yards",
  "player_rush_attempts":"Rush Attempts",
  "player_rush_longest":"Longest Rush",
  "player_receptions":"Receptions",
  "player_reception_yds":"Reception Yards",
  "player_reception_longest":"Longest Reception",
  "player_kicking_points":"Kicking Points",
  "player_field_goals":"Field Goals",
  "player_tackles_assists":"Tackles + Assists",
  "player_1st_td":"First Touchdown Scorer",
  "player_last_td":"Last Touchdown Scorer",
  "player_anytime_td":"Anytime Touchdown Scorer",
  //basketball
  "player_points":"Points", //also covers hockey
  "player_rebounds":"Rebounds",
  "player_assists":"Assists", //also covers hockey
  "player_threes":"Threes",
  "player_blocks":"Blocks",
  "player_steals":"Steals",
  "player_turnovers":"Turnovers",
  "player_points_rebounds_assists":"Points + Rebounds + Assists",
  "player_points_rebounds":"Points + Rebounds",
  "player_points_assists":"Points + Assists",
  "player_rebounds_assists":"Rebounds + Assists",
  "player_first_basket":"First Basket Scorer",
  "player_double_double":"Double Double",
  "player_triple_double":"Triple Double",
  //baseball
  "batter_home_runs":"Batter Home Runs",
  "batter_first_home_run":"Batter First Home Run",
  "batter_hits":"Batter Hits",
  "batter_total_bases":"Batter Total Bases",
  "batter_rbis":"Batter RBIs",
  "batter_runs_scored":"Batter Runs Scored",
  "batter_hits_runs_rbis":"Batter Hits + Runs + RBIs",
  "batter_singles":"Batter Singles",
  "batter_doubles":"Batter Doubles",
  "batter_triples":"Batter Triples",
  "batter_walks":"Batter Walks",
  "batter_strikeouts":"Batter Strikeouts",
  "batter_stolen_bases":"Batter Stolen Bases",
  "pitcher_strikeouts":"Pitcher Strikeouts",
  "pitcher_record_a_win":"Pitcher to Record a Win",
  "pitcher_hits_allowed":"Pitcher Hits Allowed",
  "pitcher_walks":"Pitcher Walks",
  "pitcher_earned_runs":"Pitcher Earned Runs",
  "pitcher_outs":"Pitcher Outs",
  "batter_total_bases_alternate":"Alternate Batter Total Bases",
  "batter_home_runs_alternate":"Alternate Batter Home Runs",
  "batter_hits_alternate":"Alternate Batter Hits",
  "batter_rbis_alternate":"Alternate Batter RBIs",
  "pitcher_hits_allowed_alternate":"Alternate Pitcher Hits Allowed",
  "pitcher_walks_alternate":"Alternate Pitcher Walks Allowed",
  "pitcher_strikeouts_alternate":"Alternate Pitcher Strikeouts",
  //hockey
  "player_power_play_points":"Power Play Points",
  "player_blocked_shots":"Blocked Shots",
  "player_shots_on_goal":"Shots on Goal",
  "player_goals":"Goals",
  "player_total_saves":"Total Saves",
  "player_goal_scorer_first":"First Goal Scorer",
  "player_goal_scorer_last":"Last Goal Scorer",
  "player_goal_scorer_anytime":"Anytime Goal Scorer",
  "player_points_alternate":"Alternate Points",
  "player_assists_alternate":"Alternate Assists",
  "player_power_play_points_alternate":"Alternate Power Play Points",
  "player_goals_alternate":"Alternate Goals",
  "player_shots_on_goal_alternate":"Alternate Shots on Goal",
  "player_blocked_shots_alternate":"Alternate Blocked Shots",
  "player_total_saves_alternate":"Alternate Total Saves"

}

export const additional_team_prop_titles={ 
  "totals":"Full Game",
  "spreads":"Full Game",
  "h2h":"Full Game",
  "h2h_q1":"1st Quarter",
  "h2h_q2":"2nd Quarter",
  "h2h_q3":"3rd Quarter",
  "h2h_q4":"4th Quarter",
  "h2h_h1":"1st Half",
  "h2h_h2":"2nd Half",
  "spreads_q1":"1st Quarter",
  "spreads_q2":"2nd Quarter",
  "spreads_q3":"3rd Quarter",
  "spreads_q4":"4th Quarter",
  "spreads_h1":"1st Half",
  "spreads_h2":"2nd Half",
  "totals_q1":"1st Quarter",
  "totals_q2":"2nd Quarter",
  "totals_q3":"3rd Quarter",
  "totals_q4":"4th Quarter",
  "totals_h1":"1st Half",
  "totals_h2":"2nd Half",
  "h2h_1st_1_innings":"1st Inning",
  "h2h_1st_3_innings":"1st 3 Innings",
  "h2h_1st_5_innings":"1st 5 Innings",
  "h2h_1st_7_innings":"1st 7 Innings",
  "spreads_1st_1_innings":"1st Inning",
  "spreads_1st_3_innings":"1st 3 Innings",
  "spreads_1st_5_innings":"1st 5 Innings",
  "spreads_1st_7_innings":"1st 7 Innings",
  "totals_1st_1_innings":"1st Inning",
  "totals_1st_3_innings":"1st 3 Innings",
  "totals_1st_5_innings":"1st 5 Innings",
  "totals_1st_7_innings":"1st 7 Innings",
  "h2h_p1":"1st Period",
  "h2h_p2":"2nd Period",
  "h2h_p3":"3rd Period",
  "spreads_p1":"1st Period",
  "spreads_p2":"2nd Period",
  "spreads_p3":"3rd Period",
  "totals_p1":"1st Period",
  "totals_p2":"2nd Period",
  "totals_p3":"3rd Period",
}

export const team_prop_titles={ 
    "totals":"Total",
    "spreads":"Spread",
    "h2h":"Moneyline",
    "alternate_spreads":"Alternate Spreads",
    "alternate_totals":"Alternate Totals"
  }

export const bookmaker_links={ 
  "betmgm":"https://sports.betmgm.com/en/sports",
  "bovada":"https://www.bovada.lv/",
  "betrivers":"https://betrivers.com/?page=landing#home",
  "draftkings":"https://www.draftkings.com/",
  "fanduel":"https://sportsbook.fanduel.com/",
  "pointsbetus":"https://pointsbet.com/",
  "superbook":"https://co.superbook.com/sports",
  "unibet_us":"https://unibet.com/",
  "williamhill_us":"https://www.caesars.com/sportsbook-and-casino",
  "wynnbet":"https://www.wynnbet.com/",
  "betparx":"https://betparx.com/#home",
  "espnbet":"https://espnbet.com/",
  "fliff":"https://www.getfliff.com/",
  "hardrockbet":"https://app.hardrock.bet/",
  "sisportsbook":"https://www.sisportsbook.com/",
  "tipico_us":"https://sportsbook-nj.tipico.us/home",
  "windcreek":"https://play.windcreekcasino.com/sports/",
  "prizepicks":"PrizePicks",
  "underdog":"Underdog"
}

export const bookmaker_names={ 
    "betmgm":"BetMGM",
    "bovada":"Bovada",
    "betrivers":"BetRivers",
    "draftkings":"DraftKings",
    "fanduel":"FanDuel",
    "pointsbetus":"PointsBet",
    "superbook":"Superbook",
    "unibet_us":"Unibet",
    "williamhill_us":"Caesars",
    "wynnbet":"WynnBET",
    "betparx":"betPARX",
    "espnbet":"ESPN_BET",
    "fliff":"Fliff",
	"hardrockbet":"Hard_Rock",
    "sisportsbook":"SI_Sportsbook",
    "tipico_us":"Tipico",
    "windcreek":"Wind_Creek",
	"prizepicks":"PrizePicks",
	"underdog":"Underdog"
}

export const team_codes={
    "Over":"O",
    "Under":"U",
    //mlb
    "National League":"NL",
    "American League":"AL",
    "Arizona Diamondbacks":"ARI",
    "Atlanta Braves":"ATL",
    "Baltimore Orioles":"BAL",
    "Boston Red Sox":"BOS",
    "Chicago Cubs":"CHC",
    "Chicago White Sox":"CHW",
    "Cincinnati Reds":"CIN",
    "Cleveland Guardians":"CLE",
    "Colorado Rockies":"COL",
    "Detroit Tigers":"DET",
    "Houston Astros":"HOU",
    "Kansas City Royals":"KC",
    "Los Angeles Angels":"LAA",
    "Los Angeles Dodgers":"LAD",
    "Miami Marlins":"MIA",
    "Milwaukee Brewers":"MIL",
    "Minnesota Twins":"MIN",
    "New York Mets":"NYM",
    "New York Yankees":"NYY",
    "Oakland Athletics":"OAK",
    "Philadelphia Phillies":"PHI",
    "Pittsburgh Pirates":"PIT",
    "San Diego Padres":"SD",
    "San Francisco Giants":"SF",
    "Seattle Mariners":"SEA",
    "St. Louis Cardinals":"STL",
    "Tampa Bay Rays":"TB",
    "Texas Rangers":"TEX",
    "Toronto Blue Jays":"TOR",
    "Washington Nationals":"WSH",
    //nba
    "Atlanta Hawks":"ATL",
    "Boston Celtics":"BOS",
    "Brooklyn Nets":"BKN",
    "Charlotte Hornets":"CHA",
    "Chicago Bulls":"CHI",
    "Cleveland Cavaliers":"CLE",
    "Dallas Mavericks":"DAL",
    "Denver Nuggets":"DEN",
    "Detroit Pistons":"DET",
    "Golden State Warriors":"GSW",
    "Houston Rockets":"HOU",
    "Indiana Pacers":"IND",
    "Los Angeles Clippers":"LAC",
    "Los Angeles Lakers":"LAL",
    "Memphis Grizzlies":"MEM",
    "Miami Heat":"MIA",
    "Milwaukee Bucks":"MIL",
    "Minnesota Timberwolves":"MIN",
    "New Orleans Pelicans":"NOP",
    "New York Knicks":"NYK",
    "Oklahoma City Thunder":"OKC",
    "Orlando Magic":"ORL",
    "Philadelphia 76ers":"PHI",
    "Phoenix Suns":"PHX",
    "Portland Trail Blazers":"POR",
    "Sacramento Kings":"SAC",
    "San Antonio Spurs":"SAS",
    "Toronto Raptors":"TOR",
    "Utah Jazz":"UTA",
    "Washington Wizards":"WAS",
	//wnba
	"Atlanta Dream":"ATL",
	"Chicago Sky":"CHI",
	"Connecticut Sun":"CONN",
	"Dallas Wings":"DAL",
	"Indiana Fever":"IND",
	"Las Vegas Aces":"LV",
	"Los Angeles Sparks":"LA",
	"Minnesota Lynx":"MIN",
	"New York Liberty":"NY",
	"Phoenix Mercury":"PHX",
	"Seattle Storm":"SEA",
	"Washington Mystics":"WSH",
    //nhl
    "Anaheim Ducks":"ANA",
    "Arizona Coyotes":"ARI",
    "Boston Bruins":"BOS",
    "Buffalo Sabres":"BUF",
    "Calgary Flames":"CGY",
    "Carolina Hurricanes":"CAR",
    "Chicago Blackhawks":"CHI",
    "Colorado Avalanche":"COL",
    "Columbus Blue Jackets":"CBJ",
    "Dallas Stars":"DAL",
    "Detriot Red Wings":"DET",
    "Edmonton Oilers":"EDM",
    "Florida Panthers":"FLA",
    "Los Angeles Kings":"LA",
    "Minnesota Wild":"MIN",
    "Montréal Canadiens":"MTL",
    "Nashville Predators":"NSH",
    "New Jersey Devils":"NJ",
    "New York Islanders":"NYI",
    "New York Rangers":"NYR",
    "Ottawa Senators":"OTT",
    "Philadelphia Flyers":"PHI",
    "Pittsburgh Penguins":"PIT",
    "San Jose Sharks":"SJ",
    "Seattle Kraken":"SEA",
    "St Louis Blues":"STL",
    "Tampa Bay Lightning":"TB",
    "Toronto Maple Leafs":"TOR",
    "Vancouver Canucks":"VAN",
    "Vegas Golden Knights":"VGK",
    "Washington Capitals":"WSH",
    "Winnipeg Jets":"WPG",
    //nfl
    "Arizona Cardinals":"ARI",
    "Atlanta Falcons":"ATL",
    "Baltimore Ravens":"BAL",
    "Buffalo Bills":"BUF",
    "Carolina Panthers":"CAR",
    "Chicago Bears":"CHI",
    "Cincinnati Bengals":"CIN",
    "Cleveland Browns":"CLE",
    "Dallas Cowboys":"DAL",
    "Denver Broncos":"DEN",
    "Detroit Lions":"DET",
    "Green Bay Packers":"GB",
    "Houston Texans":"HOU",
    "Indianapolis Colts":"IND",
    "Jacksonville Jaguars":"JAX",
    "Kansas City Chiefs":"KC",
    "Las Vegas Raiders":"LV",
    "Los Angeles Chargers":"LAC",
    "Los Angeles Rams":"LAR",
    "Miami Dolphins":"MIA",
    "Minnesota Vikings":"MIN",
    "New England Patriots":"NE",
    "New Orleans Saints":"NO",
    "New York Giants":"NYG",
    "New York Jets":"NYJ",
    "Philadelphia Eagles":"PHI",
    "Pittsburgh Steelers":"PIT",
    "San Francisco 49ers":"SF",
    "Seattle Seahawks":"SEA",
    "Tampa Bay Buccaneers":"TB",
    "Tennessee Titans":"TEN",
    "Washington Commanders":"WAS",
    //NCAAF && ncaab
    "Abilene Christian Wildcats": "ACU",
	"Air Force Falcons": "AIR",
	"Akron Zips": "AKRON",
	"Alabama A&M Bulldogs": "ALAAM",
	"Alabama Crimson Tide": "BAMA",
	"Alabama St Hornets": "ALASU",
	"Albany Great Danes": "ALBNY",
	"Alcorn St Braves": "ALCST",
	"American Eagles": "AMRCA",
	"Appalachian St Mountaineers": "APPST",
	"Appalachian State Mountaineers": "APPST",
	"Arizona St Sun Devils": "ASU",
	"Arizona State Sun Devils": "ASU",
	"Arizona Wildcats": "ARZ",
	"Arkansas Razorbacks": "ARK",
	"Arkansas St Red Wolves": "ARKST",
	"Arkansas State Red Wolves": "ARKST",
	"Arkansas-Little Rock Trojans": "LITTL",
	"Arkansas-Pine Bluff Golden Lions": "ARPB",
	"Army Black Knights": "ARMY",
	"Army Knights": "ARMY",
	"Auburn Tigers": "AUB",
	"Austin Peay Governors": "AUSPE",
	"BYU Cougars": "BYU",
	"Ball State Cardinals": "BALL",
	"Baylor Bears": "BAYL",
	"Bellarmine Knights": "BELLA",
	"Belmont Bruins": "BELM",
	"Bethune-Cookman Wildcats": "BCOOK",
	"Binghamton Bearcats": "BING",
	"Boise State Broncos": "BOISE",
	"Boston College Eagles": "BC",
	"Boston Univ. Terriers": "BU",
	"Bowling Green Falcons": "BOWL",
	"Bradley Braves": "BRAD",
	"Bryant Bulldogs": "BRYNT",
	"Bucknell Bison": "BUCK",
	"Buffalo Bulls": "BUF",
	"Butler Bulldogs": "BUTL",
	"CSU Bakersfield Roadrunners": "CSUBK",
	"CSU Fullerton Titans": "CSUFL",
	"CSU Northridge Matadors": "CSUNR",
	"Cal Baptist Lancers": "CALBP",
	"Cal Poly Mustangs": "CPOLY",
	"California Golden Bears": "CALI",
	"Campbell Fighting Camels": "CAMPB",
	"Canisius Golden Griffins": "CANS",
	"Central Arkansas Bears": "UCA",
	"Central Connecticut St Blue Devils": "CCSU",
	"Central Michigan Chippewas": "CMICH",
	"Charleston Cougars": "CHRL",
	"Charleston Southern Buccaneers": "SCHRL",
	"Charlotte 49ers": "CHRLT",
	"Chattanooga Mocs": "CHATT",
	"Cincinnati Bearcats": "CIN",
	"Clemson Tigers": "CLEM",
	"Cleveland St Vikings": "CLEST",
	"Coastal Carolina Chanticleers": "COAST",
	"Colorado Buffaloes": "COL",
	"Colorado St Rams": "COLST",
	"Colorado State Rams": "COLST",
	"Coppin St Eagles": "COPST",
	"Creighton Bluejays": "CREI",
	"Davidson Wildcats": "DAVID",
	"Dayton Flyers": "DAYT",
	"DePaul Blue Demons": "DEPAU",
	"Delaware Blue Hens": "UD",
	"Delaware St Hornets": "DELST",
	"Denver Pioneers": "DEN",
	"Detroit Mercy Titans": "DMERC",
	"Drake Bulldogs": "DRAKE",
	"Drexel Dragons": "DREX",
	"Duke Blue Devils": "DUKE",
	"Duquesne Dukes": "DUQ",
	"East Carolina Pirates": "ECU",
	"East Tennessee St Buccaneers": "ETNST",
	"Eastern Illinois Panthers": "EILL",
	"Eastern Kentucky Colonels": "EKENT",
	"Eastern Michigan Eagles": "EMICH",
	"Eastern Washington Eagles": "EWASH",
	"Elon Phoenix": "ELON",
	"Fairleigh Dickinson Knights": "FAIRL",
	"Florida A&M Rattlers": "FLAM",
	"Florida Atlantic Owls": "FAU",
	"Florida Gators": "UFL",
	"Florida Gulf Coast Eagles": "FGCU",
	"Florida Int'l Golden Panthers": "FIU",
	"Florida International Panthers": "FIU",
	"Florida St Seminoles": "FSU",
	"Florida State Seminoles": "FSU",
	"Fordham Rams": "FORD",
	"Fort Wayne Mastodons": "FORTW",
	"Fresno St Bulldogs": "FRES",
	"Fresno State Bulldogs": "FRES",
	"Furman Paladins": "FURM",
	"GW Revolutionaries": "GW",
	"Gardner-Webb Bulldogs": "GWEBB",
	"George Mason Patriots": "GMSN",
	"George Washington Colonials": "GW",
	"Georgetown Hoyas": "GEOR",
	"Georgia Bulldogs": "UGA",
	"Georgia Southern Eagles": "GASOU",
	"Georgia St Panthers": "GAST",
	"Georgia State Panthers": "GAST",
	"Georgia Tech Yellow Jackets": "GTECH",
	"Gonzaga Bulldogs": "GONZ",
	"Grambling St Tigers": "GRAM",
	"Grand Canyon Antelopes": "GRAND",
	"Green Bay Phoenix": "GB",
	"Hampton Pirates": "HAMP",
	"Hawai'i Rainbow Warriors": "HWI",
	"Hawaii Rainbow Warriors": "HWI",
	"High Point Panthers": "HIGH",
	"Hofstra Pride": "HOFST",
	"Holy Cross Crusaders": "HOLY",
	"Houston Baptist Huskies": "HCU",
	"Houston Cougars": "HOU",
	"Howard Bison": "HWRD",
	"IUPUI Jaguars": "IUPUI",
	"Idaho Vandals": "UIDA",
	"Illinois Fighting Illini": "ILL",
	"Illinois St Redbirds": "ILLST",
	"Incarnate Word Cardinals": "INCAR",
	"Indiana Hoosiers": "INDU",
	"Indiana St Sycamores": "INDST",
	"Iowa Hawkeyes": "IOWA",
	"Iowa State Cyclones": "IAST",
	"Jackson St Tigers": "JXST",
	"Jacksonville Dolphins": "JAX",
	"Jacksonville St Gamecocks": "JSU",
	"Jacksonville State Gamecocks": "JSU",
	"James Madison Dukes": "JMU",
	"Kansas Jayhawks": "KU",
	"Kansas St Wildcats": "KSU",
	"Kansas State Wildcats": "KSU",
	"Kennesaw St Owls": "KENST",
	"Kent State Golden Flashes": "KENT",
	"Kentucky Wildcats": "UK",
	"LIU Sharks": "LIU",
	"LSU Tigers": "LSU",
	"La Salle Explorers": "LASAL",
	"Lafayette Leopards": "LAFAY",
	"Liberty Flames": "LIB",
	"Lindenwood Lions": "LINDW",
	"Lipscomb Bisons": "LIPSC",
	"Long Beach St 49ers": "LBSU",
	"Longwood Lancers": "LONG",
	"Louisiana Ragin Cajuns": "UL",
	"Louisiana Ragin' Cajuns": "UL",
	"Louisiana Tech Bulldogs": "LTECH",
	"Louisville Cardinals": "LOU",
	"Loyola (Chi) Ramblers": "LOYCH",
	"Loyola (MD) Greyhounds": "LOYMD",
	"Loyola Marymount Lions": "LOYOL",
	"Maine Black Bears": "MAINE",
	"Marquette Golden Eagles": "MARQ",
	"Marshall Thundering Herd": "MARSH",
	"Maryland Terrapins": "MARY",
	"Maryland-Eastern Shore Hawks": "MDES",
	"Massachusetts Minutemen": "UMAS",
	"McNeese Cowboys": "MCNE",
	"Memphis Tigers": "MEM",
	"Mercer Bears": "MRCER",
	"Merrimack Warriors": "MERRI",
	"Miami (OH) RedHawks": "MIAOH",
	"Miami Hurricanes": "MIA",
	"Michigan St Spartans": "MSU",
	"Michigan State Spartans": "MSU",
	"Michigan Wolverines": "MICH",
	"Middle Tennessee Blue Raiders": "MTNST",
	"Milwaukee Panthers": "MILWA",
	"Minnesota Golden Gophers": "MIN",
	"Mississippi St Bulldogs": "MISST",
	"Mississippi State Bulldogs": "MISST",
	"Missouri St Bears": "MIZST",
	"Missouri Tigers": "MIZZ",
	"Monmouth Hawks": "MONMO",
	"Montana Grizzlies": "MONTA",
	"Montana St Bobcats": "MONST",
	"Morgan St Bears": "MRGST",
	"Mt. St. Mary's Mountaineers": "MSMU",
	"Murray St Racers": "MURST",
	"N Colorado Bears": "NCOL",
	"NC State Wolfpack": "NCSU",
	"NJIT Highlanders": "NJIT",
	"Navy Midshipmen": "NAVY",
	"Nebraska Cornhuskers": "NEB",
	"Nevada Wolf Pack": "NEVA",
	"New Hampshire Wildcats": "NHAMP",
	"New Mexico Lobos": "NMEX",
	"New Mexico St Aggies": "NMXST",
	"New Mexico State Aggies": "NMXST",
	"New Orleans Privateers": "NO",
	"Niagara Purple Eagles": "NIAG",
	"Nicholls St Colonels": "NICHL",
	"Norfolk St Spartans": "NORST",
	"North Alabama Lions": "NALA",
	"North Carolina A&T Aggies": "NCA&T",
	"North Carolina Central Eagles": "NCC",
	"North Carolina Tar Heels": "UNC",
	"North Dakota St Bison": "NDSU",
	"North Florida Ospreys": "UNF",
	"North Texas Mean Green": "NTX",
	"Northeastern Huskies": "NEU",
	"Northern Arizona Lumberjacks": "NARIZ",
	"Northern Illinois Huskies": "NIU",
	"Northern Iowa Panthers": "UNI",
	"Northern Kentucky Norse": "NKENT",
	"Northwestern St Demons": "NWST",
	"Northwestern Wildcats": "NWU",
	"Notre Dame Fighting Irish": "ND",
	"Oakland Golden Grizzlies": "OAK",
	"Ohio Bobcats": "OHIO",
	"Ohio State Buckeyes": "OSU",
	"Oklahoma Sooners": "OU",
	"Oklahoma St Cowboys": "OKST",
	"Oklahoma State Cowboys": "OKST",
	"Old Dominion Monarchs": "OLD",
	"Ole Miss Rebels": "OLE",
	"Omaha Mavericks": "UNO",
	"Oral Roberts Golden Eagles": "ORAL",
	"Oregon Ducks": "ORE",
	"Oregon St Beavers": "OREST",
	"Oregon State Beavers": "OREST",
	"Pacific Tigers": "PACIF",
	"Penn State Nittany Lions": "PSU",
	"Pepperdine Waves": "PEPP",
	"Pittsburgh Panthers": "PITT",
	"Portland Pilots": "PORT",
	"Portland St Vikings": "PRTST",
	"Prairie View Panthers": "PVAM",
	"Providence Friars": "PROV",
	"Purdue Boilermakers": "PUR",
	"Queens University Royals": "QUEEN",
	"Quinnipiac Bobcats": "QUIN",
	"Rhode Island Rams": "URI",
	"Rice Owls": "RICE",
	"Richmond Spiders": "RICH",
	"Rider Broncs": "RIDER",
	"Rutgers Scarlet Knights": "RUTG",
	"SE Louisiana Lions": "SELOU",
	"SE Missouri St Redhawks": "SEMO",
	"SMU Mustangs": "SMU",
	"Sacramento St Hornets": "SACST",
	"Sacred Heart Pioneers": "HEART",
	"Saint Joseph's Hawks": "STJOE",
	"Saint Louis Billikens": "STLOU",
	"Saint Mary's Gaels": "STMAR",
	"Saint Peter's Peacocks": "STP",
	"Sam Houston St Bearkats": "SMHO",
	"Sam Houston State Bearkats": "SMHO",
	"Samford Bulldogs": "SAMFO",
	"San Diego St Aztecs": "SDSU",
	"San Diego State Aztecs": "SDSU",
	"San Diego Toreros": "SD",
	"San Francisco Dons": "SF",
	"San Jose State Spartans": "SJSU",
	"San José St Spartans": "SJSU",
	"Santa Clara Broncos": "SANCL",
	"Seton Hall Pirates": "SETON",
	"South Alabama Jaguars": "SALA",
	"South Carolina Gamecocks": "SC",
	"South Carolina St Bulldogs": "SCST",
	"South Carolina Upstate Spartans": "USCU",
	"South Dakota Coyotes": "SDAK",
	"South Dakota St Jackrabbits": "SDKST",
	"South Florida Bulls": "USF",
	"Southern Illinois Salukis": "SIU",
	"Southern Indiana Screaming Eagles": "USI",
	"Southern Jaguars": "SOUTH",
	"Southern Miss Golden Eagles": "SMISS",
	"Southern Mississippi Golden Eagles": "SMISS",
	"Southern Utah Thunderbirds": "SUTAH",
	"St. Bonaventure Bonnies": "STBON",
	"St. Francis (PA) Red Flash": "STFRA",
	"St. John's Red Storm": "SJU",
	"St. Thomas (MN) Tommies": "STTHO",
	"Stanford Cardinal": "STAN",
	"Stephen F. Austin Lumberjacks": "SFA",
	"Stetson Hatters": "STET",
	"Stonehill Skyhawks": "STNHL",
	"Stony Brook Seawolves": "STONY",
	"Syracuse Orange": "SYR",
	"TCU Horned Frogs": "TCU",
	"Tarleton State Texans": "TARL",
	"Temple Owls": "TEMP",
	"Tenn-Martin Skyhawks": "UTMAR",
	"Tennessee Tech Golden Eagles": "TNTEC",
	"Tennessee Volunteers": "TENN",
	"Texas A&M Aggies": "A&M",
	"Texas A&M-Commerce Lions": "TXAMC",
	"Texas Longhorns": "TEX",
	"Texas State Bobcats": "TXST",
	"Texas Tech Red Raiders": "TTU",
	"The Citadel Bulldogs": "CITAD",
	"Toledo Rockets": "TOL",
	"Towson Tigers": "TOWSO",
	"Troy Trojans": "TROY",
	"Tulane Green Wave": "TUL",
	"Tulsa Golden Hurricane": "TULSA",
	"UAB Blazers": "UAB",
	"UC Irvine Anteaters": "UCIRV",
	"UC Riverside Highlanders": "UCRIV",
	"UC San Diego Tritons": "UCSD",
	"UC Santa Barbara Gauchos": "UCSB",
	"UCF Knights": "UCF",
	"UCLA Bruins": "UCLA",
	"UConn Huskies": "UCONN",
	"UIC Flames": "UIC",
	"UL Monroe Warhawks": "ULMON",
	"UMKC Kangaroos": "UKC",
	"UMass Lowell River Hawks": "UML",
	"UMass Minutemen": "UMAS",
	"UNC Greensboro Spartans": "NCGRE",
	"UNC Wilmington Seahawks": "NCWLM",
	"UNLV Rebels": "UNLV",
	"USC Trojans": "USC",
	"UT Rio Grande Valley Vaqueros": "UTRIO",
	"UTEP Miners": "UTEP",
	"UTSA Roadrunners": "UTSA",
	"Utah State Aggies": "USU",
	"Utah Tech Trailblazers": "UTECH",
	"Utah Utes": "UTAH",
	"VCU Rams": "VCU",
	"Valparaiso Beacons": "VALPA",
	"Vanderbilt Commodores": "VND",
	"Vermont Catamounts": "VERMO",
	"Villanova Wildcats": "NOVA",
	"Virginia Cavaliers": "VIR",
	"Virginia Tech Hokies": "VTECH",
	"Wagner Seahawks": "WAG",
	"Wake Forest Demon Deacons": "WAKE",
	"Washington Huskies": "WASH",
	"Washington St Cougars": "WSU",
	"Washington State Cougars": "WSU",
	"West Virginia Mountaineers": "WVU",
	"Western Carolina Catamounts": "WCARO",
	"Western Illinois Leathernecks": "WILLI",
	"Western Kentucky Hilltoppers": "WKY",
	"Western Michigan Broncos": "WMICH",
	"Wichita St Shockers": "WICH",
	"William & Mary Tribe": "W&M",
	"William and Mary Tribe": "W&M",
	"Winthrop Eagles": "WINTH",
	"Wisconsin Badgers": "WISC",
	"Wofford Terriers": "WOFF",
	"Wright St Raiders": "WRGHT",
	"Wyoming Cowboys": "WYOM",
	"Xavier Musketeers": "XAV",
	"Youngstown St Penguins": "YNGST",
	"Columbia Lions":"COLUM",
	"Brown Bears":"BROWN",
	"Iona Gaels":"IONA",
	"VMI Keydets":"VMI",
	"UMBC Retrievers":"UMBC",
	"Cornell Big Red":"CORN",
	"Yale Bulldogs":"YALE",
	"Dartmouth Big Green":"DART",
	"Harvard Crimson":"HARV",
	"Fairfield Stags":"FAIR",
	"Robert Morris Colonials":"RMU",
	"Texas A&M Commerce":"TXAMC",
	"North Dakota Fighting Hawks":"UND",
	"Chicago St Cougars":"CHIST",
	"Le Moyne Dolphins":"LEMYN",
	"UT-Arlington Mavericks":"UTARL",
	"Morehead St Eagles":"MHST",
	"Utah Valley Wolverines":"UTAHV",
	"Evansville Purple Aces":"EVANS",
	"Texas Southern Tigers":"TXS",
	"UNC Asheville Bulldogs":"NCASH",
	"Presbyterian Blue Hose":"PRESB",
	"Radford Highlanders":"RADF",
	"Tennessee St Tigers":"TNST",
	"Colgate Raiders":"COLG",
	"Texas A&M-CC Islanders":"TAMU",
	"Pennsylvania Quakers":"UPENN",
	"Princeton Tigers":"PRNCE",
	"Seattle Redhawks":"SEA",
	"Miss Valley St Delta Devils":"MSVST",
	"Lehigh Mountain Hawks":"LEHGH",
	"Lamar Cardinals":"LAMAR",
	"Marist Red Foxes":"MRIST",
	"Siena Saints":"SIENA",
	"Manhattan Jaspers":"MANH",
	"Idaho State Bengals":"IDST",
	"SIU-Edwardsville Cougars":"SIUE",
	"Weber State Wildcats":"WEBST",
	"UC Davis Aggies":"UCDV",
}


export const team_titles={
  //mlb
  "National League":"NL",
  "American League":"AL",
  "Arizona Diamondbacks":"ARI",
  "Atlanta Braves":"ATL",
  "Baltimore Orioles":"BAL",
  "Boston Red Sox":"BOS",
  "Chicago Cubs":"CHC",
  "Chicago White Sox":"CHW",
  "Cincinnati Reds":"CIN",
  "Cleveland Guardians":"CLE",
  "Colorado Rockies":"COL",
  "Detroit Tigers":"DET",
  "Houston Astros":"HOU",
  "Kansas City Royals":"KC",
  "Los Angeles Angels":"LAA",
  "Los Angeles Dodgers":"LAD",
  "Miami Marlins":"MIA",
  "Milwaukee Brewers":"MIL",
  "Minnesota Twins":"MIN",
  "New York Mets":"NYM",
  "New York Yankees":"NYY",
  "Oakland Athletics":"OAK",
  "Philadelphia Phillies":"PHI",
  "Pittsburgh Pirates":"PIT",
  "San Diego Padres":"SD",
  "San Francisco Giants":"SF",
  "Seattle Mariners":"SEA",
  "St. Louis Cardinals":"STL",
  "Tampa Bay Rays":"TB",
  "Texas Rangers":"TEX",
  "Toronto Blue Jays":"TOR",
  "Washington Nationals":"WSH",
  //nba
  "Atlanta Hawks":"ATL",
  "Boston Celtics":"BOS",
  "Brooklyn Nets":"BKN",
  "Charlotte Hornets":"CHA",
  "Chicago Bulls":"CHI",
  "Cleveland Cavaliers":"CLE",
  "Dallas Mavericks":"DAL",
  "Denver Nuggets":"DEN",
  "Detroit Pistons":"DET",
  "Golden State Warriors":"GSW",
  "Houston Rockets":"HOU",
  "Indiana Pacers":"IND",
  "Los Angeles Clippers":"LAC",
  "Los Angeles Lakers":"LAL",
  "Memphis Grizzlies":"MEM",
  "Miami Heat":"MIA",
  "Milwaukee Bucks":"MIL",
  "Minnesota Timberwolves":"MIN",
  "New Orleans Pelicans":"NOP",
  "New York Knicks":"NYK",
  "Oklahoma City Thunder":"OKC",
  "Orlando Magic":"ORL",
  "Philadelphia 76ers":"PHI",
  "Phoenix Suns":"PHX",
  "Portland Trail Blazers":"POR",
  "Sacramento Kings":"SAC",
  "San Antonio Spurs":"SAS",
  "Toronto Raptors":"TOR",
  "Utah Jazz":"UTA",
  "Washington Wizards":"WAS",
  //wnba
  "Atlanta Dream":"ATL",
	"Chicago Sky":"CHI",
	"Connecticut Sun":"CONN",
	"Dallas Wings":"DAL",
	"Indiana Fever":"IND",
	"Las Vegas Aces":"LV",
	"Los Angeles Sparks":"LA",
	"Minnesota Lynx":"MIN",
	"New York Liberty":"NY",
	"Phoenix Mercury":"PHX",
	"Seattle Storm":"SEA",
	"Washington Mystics":"WSH",
  //nhl
  "Anaheim Ducks":"ANA",
  "Arizona Coyotes":"ARI",
  "Boston Bruins":"BOS",
  "Buffalo Sabres":"BUF",
  "Calgary Flames":"CGY",
  "Carolina Hurricanes":"CAR",
  "Chicago Blackhawks":"CHI",
  "Colorado Avalanche":"COL",
  "Columbus Blue Jackets":"CBJ",
  "Dallas Stars":"DAL",
  "Detriot Red Wings":"DET",
  "Edmonton Oilers":"EDM",
  "Florida Panthers":"FLA",
  "Los Angeles Kings":"LA",
  "Minnesota Wild":"MIN",
  "Montréal Canadiens":"MTL",
  "Nashville Predators":"NSH",
  "New Jersey Devils":"NJ",
  "New York Islanders":"NYI",
  "New York Rangers":"NYR",
  "Ottawa Senators":"OTT",
  "Philadelphia Flyers":"PHI",
  "Pittsburgh Penguins":"PIT",
  "San Jose Sharks":"SJ",
  "Seattle Kraken":"SEA",
  "St Louis Blues":"STL",
  "Tampa Bay Lightning":"TB",
  "Toronto Maple Leafs":"TOR",
  "Vancouver Canucks":"VAN",
  "Vegas Golden Knights":"VGK",
  "Washington Capitals":"WSH",
  "Winnipeg Jets":"WPG",
  //nfl
  "Arizona Cardinals":"ARI",
  "Atlanta Falcons":"ATL",
  "Baltimore Ravens":"BAL",
  "Buffalo Bills":"BUF",
  "Carolina Panthers":"CAR",
  "Chicago Bears":"CHI",
  "Cincinnati Bengals":"CIN",
  "Cleveland Browns":"CLE",
  "Dallas Cowboys":"DAL",
  "Denver Broncos":"DEN",
  "Detroit Lions":"DET",
  "Green Bay Packers":"GB",
  "Houston Texans":"HOU",
  "Indianapolis Colts":"IND",
  "Jacksonville Jaguars":"JAX",
  "Kansas City Chiefs":"KC",
  "Las Vegas Raiders":"LV",
  "Los Angeles Chargers":"LAC",
  "Los Angeles Rams":"LAR",
  "Miami Dolphins":"MIA",
  "Minnesota Vikings":"MIN",
  "New England Patriots":"NE",
  "New Orleans Saints":"NO",
  "New York Giants":"NYG",
  "New York Jets":"NYJ",
  "Philadelphia Eagles":"PHI",
  "Pittsburgh Steelers":"PIT",
  "San Francisco 49ers":"SF",
  "Seattle Seahawks":"SEA",
  "Tampa Bay Buccaneers":"TB",
  "Tennessee Titans":"TEN",
  "Washington Commanders":"WAS",
  //NCAAF & NCAAB
  "Abilene Christian Wildcats": "Abilene Christian",
	"Air Force Falcons": "Air Force",
	"Akron Zips": "Akron",
	"Alabama A&M Bulldogs": "Alabama A&M",
	"Alabama Crimson Tide": "Alabama",
	"Alabama St Hornets": "Alabama State",
	"Albany Great Danes": "Albany",
	"Alcorn St Braves": "Alcorn State",
	"American Eagles": "American",
	"Appalachian St Mountaineers": "Appalachian State",
	"Appalachian State Mountaineers": "Appalachian State",
	"Arizona St Sun Devils": "Arizona State",
	"Arizona State Sun Devils": "Arizona State",
	"Arizona Wildcats": "Arizona",
	"Arkansas Razorbacks": "Arkansas",
	"Arkansas St Red Wolves": "Arkansas State",
	"Arkansas State Red Wolves": "Arkansas State",
	"Arkansas-Little Rock Trojans": "Little Rock",
	"Arkansas-Pine Bluff Golden Lions": "Arkansas-Pine Bluff",
	"Army Black Knights": "Army",
	"Army Knights": "Army",
	"Auburn Tigers": "Auburn",
	"Austin Peay Governors": "Austin Peay",
	"BYU Cougars": "BYU",
	"Ball State Cardinals": "Ball State",
	"Baylor Bears": "Baylor",
	"Bellarmine Knights": "Bellarmine",
	"Belmont Bruins": "Belmont",
	"Bethune-Cookman Wildcats": "Bethune-Cookman",
	"Binghamton Bearcats": "Binghamton",
	"Boise State Broncos": "Boise State",
	"Boston College Eagles": "Boston College",
	"Boston Univ. Terriers": "Boston University",
	"Bowling Green Falcons": "Bowling Green",
	"Bradley Braves": "Bradley",
	"Bryant Bulldogs": "Bryant",
	"Bucknell Bison": "Bucknell",
	"Buffalo Bulls": "Buffalo",
	"Butler Bulldogs": "Butler",
	"CSU Bakersfield Roadrunners": "CSU Bakersfield",
	"CSU Fullerton Titans": "CSU Fullerton",
	"CSU Northridge Matadors": "CSU Northridge",
	"Cal Baptist Lancers": "California Baptist",
	"Cal Poly Mustangs": "Cal Poly",
	"California Golden Bears": "California",
	"Campbell Fighting Camels": "Campbell",
	"Canisius Golden Griffins": "Canisius",
	"Central Arkansas Bears": "Central Arkansas",
	"Central Connecticut St Blue Devils": "Cent. Conn. St.",
	"Central Michigan Chippewas": "Central Michigan",
	"Charleston Cougars": "Charleston",
	"Charleston Southern Buccaneers": "Charleston Southern",
	"Charlotte 49ers": "Charlotte",
	"Chattanooga Mocs": "Chattanooga",
	"Cincinnati Bearcats": "Cincinnati",
	"Clemson Tigers": "Clemson",
	"Cleveland St Vikings": "Cleveland State",
	"Coastal Carolina Chanticleers": "Coastal Carolina",
	"Colorado Buffaloes": "Colorado",
	"Colorado St Rams": "Colorado State",
	"Colorado State Rams": "Colorado State",
	"Coppin St Eagles": "Coppin State",
	"Creighton Bluejays": "Creighton",
	"Davidson Wildcats": "Davidson",
	"Dayton Flyers": "Dayton",
	"DePaul Blue Demons": "DePaul",
	"Delaware Blue Hens": "Delaware",
	"Delaware St Hornets": "Delaware State",
	"Denver Pioneers": "Denver",
	"Detroit Mercy Titans": "Detroit Mercy",
	"Drake Bulldogs": "Drake",
	"Drexel Dragons": "Drexel",
	"Duke Blue Devils": "Duke",
	"Duquesne Dukes": "Duquesne",
	"East Carolina Pirates": "East Carolina",
	"East Tennessee St Buccaneers": "East Tennessee",
	"Eastern Illinois Panthers": "Eastern Illinois",
	"Eastern Kentucky Colonels": "Eastern Kentucky",
	"Eastern Michigan Eagles": "Eastern Michigan",
	"Eastern Washington Eagles": "Eastern Washington",
	"Elon Phoenix": "Elon",
	"Fairleigh Dickinson Knights": "Fairleigh Dickinson",
	"Florida A&M Rattlers": "Florida A&M",
	"Florida Atlantic Owls": "Florida Atlantic",
	"Florida Gators": "Florida",
	"Florida Gulf Coast Eagles": "Florida Gulf Coast",
	"Florida Int'l Golden Panthers": "Florida International",
	"Florida International Panthers": "Florida International",
	"Florida St Seminoles": "Florida State",
	"Florida State Seminoles": "Florida State",
	"Fordham Rams": "Fordham",
	"Fort Wayne Mastodons": "Fort Wayne",
	"Fresno St Bulldogs": "Fresno State",
	"Fresno State Bulldogs": "Fresno State",
	"Furman Paladins": "Furman",
	"GW Revolutionaries": "George Washington",
	"Gardner-Webb Bulldogs": "Gardner-Webb",
	"George Mason Patriots": "George Mason",
	"George Washington Colonials": "George Washington",
	"Georgetown Hoyas": "Georgetown",
	"Georgia Bulldogs": "Georgia",
	"Georgia Southern Eagles": "Georgia Southern",
	"Georgia St Panthers": "Georgia State",
	"Georgia State Panthers": "Georgia State",
	"Georgia Tech Yellow Jackets": "Georgia Tech",
	"Gonzaga Bulldogs": "Gonzaga",
	"Grambling St Tigers": "Grambling",
	"Grand Canyon Antelopes": "Grand Canyon",
	"Green Bay Phoenix": "Green Bay",
	"Hampton Pirates": "Hampton",
	"Hawai'i Rainbow Warriors": "Hawaii",
	"Hawaii Rainbow Warriors": "Hawaii",
	"High Point Panthers": "High Point",
	"Hofstra Pride": "Hofstra",
	"Holy Cross Crusaders": "Holy Cross",
	"Houston Baptist Huskies": "Houston Christian",
	"Houston Cougars": "Houston",
	"Howard Bison": "Howard",
	"IUPUI Jaguars": "IUPUI",
	"Idaho Vandals": "Idaho",
	"Illinois Fighting Illini": "Illinois",
	"Illinois St Redbirds": "Illinois State",
	"Incarnate Word Cardinals": "Incarnate Word",
	"Indiana Hoosiers": "Indiana",
	"Indiana St Sycamores": "Indiana State",
	"Iowa Hawkeyes": "Iowa",
	"Iowa State Cyclones": "Iowa State",
	"Jackson St Tigers": "Jackson State",
	"Jacksonville Dolphins": "Jacksonville",
	"Jacksonville St Gamecocks": "Jacksonville State",
	"Jacksonville State Gamecocks": "Jacksonville State",
	"James Madison Dukes": "James Madison",
	"Kansas Jayhawks": "Kansas",
	"Kansas St Wildcats": "Kansas State",
	"Kansas State Wildcats": "Kansas State",
	"Kennesaw St Owls": "Kennesaw State",
	"Kent State Golden Flashes": "Kent State",
	"Kentucky Wildcats": "Kentucky",
	"LIU Sharks": "LIU",
	"LSU Tigers": "LSU",
	"La Salle Explorers": "La Salle",
	"Lafayette Leopards": "Lafayette",
	"Liberty Flames": "Liberty",
	"Lindenwood Lions": "Lindenwood",
	"Lipscomb Bisons": "Lipscomb",
	"Long Beach St 49ers": "Long Beach State",
	"Longwood Lancers": "Longwood",
	"Louisiana Ragin Cajuns": "LA-Lafayette",
	"Louisiana Ragin' Cajuns": "LA-Lafayette",
	"Louisiana Tech Bulldogs": "Louisiana Tech",
	"Louisville Cardinals": "Louisville",
	"Loyola (Chi) Ramblers": "Loyola Chicago",
	"Loyola (MD) Greyhounds": "Loyola MD",
	"Loyola Marymount Lions": "Loyola Marymount",
	"Maine Black Bears": "Maine",
	"Marquette Golden Eagles": "Marquette",
	"Marshall Thundering Herd": "Marshall",
	"Maryland Terrapins": "Maryland",
	"Maryland-Eastern Shore Hawks": "Maryland-Eastern Shore",
	"Massachusetts Minutemen": "Massachusetts",
	"McNeese Cowboys": "McNeese",
	"Memphis Tigers": "Memphis",
	"Mercer Bears": "Mercer",
	"Merrimack Warriors": "Merrimack",
	"Miami (OH) RedHawks": "Miami (OH)",
	"Miami Hurricanes": "Miami Florida",
	"Michigan St Spartans": "Michigan State",
	"Michigan State Spartans": "Michigan State",
	"Michigan Wolverines": "Michigan",
	"Middle Tennessee Blue Raiders": "Middle Tennessee",
	"Milwaukee Panthers": "UW Milwaukee",
	"Minnesota Golden Gophers": "Minnesota",
	"Mississippi St Bulldogs": "Mississippi State",
	"Mississippi State Bulldogs": "Mississippi State",
	"Missouri St Bears": "Missouri State",
	"Missouri Tigers": "Missouri",
	"Monmouth Hawks": "Monmouth",
	"Montana Grizzlies": "Montana",
	"Montana St Bobcats": "Montana State",
	"Morgan St Bears": "Morgan State",
	"Mt. St. Mary's Mountaineers": "Mt. St. Mary's",
	"Murray St Racers": "Murray State",
	"N Colorado Bears": "Northern Colorado",
	"NC State Wolfpack": "NC State",
	"NJIT Highlanders": "NJIT",
	"Navy Midshipmen": "Navy",
	"Nebraska Cornhuskers": "Nebraska",
	"Nevada Wolf Pack": "Nevada",
	"New Hampshire Wildcats": "New Hampshire",
	"New Mexico Lobos": "New Mexico",
	"New Mexico St Aggies": "New Mexico State",
	"New Mexico State Aggies": "New Mexico State",
	"New Orleans Privateers": "New Orleans",
	"Niagara Purple Eagles": "Niagara",
	"Nicholls St Colonels": "Nicholls",
	"Norfolk St Spartans": "Norfolk State",
	"North Alabama Lions": "North Alabama",
	"North Carolina A&T Aggies": "North Carolina A&T",
	"North Carolina Central Eagles": "North Carolina Central",
	"North Carolina Tar Heels": "UNC",
	"North Dakota St Bison": "North Dakota State",
	"North Florida Ospreys": "North Florida",
	"North Texas Mean Green": "North Texas",
	"Northeastern Huskies": "Northeastern",
	"Northern Arizona Lumberjacks": "Northern Arizona",
	"Northern Illinois Huskies": "Northern Illinois",
	"Northern Iowa Panthers": "Northern Iowa",
	"Northern Kentucky Norse": "Northern Kentucky",
	"Northwestern St Demons": "Northwestern State",
	"Northwestern Wildcats": "Northwestern",
	"Notre Dame Fighting Irish": "Notre Dame",
	"Oakland Golden Grizzlies": "Oakland",
	"Ohio Bobcats": "Ohio",
	"Ohio State Buckeyes": "Ohio State",
	"Oklahoma Sooners": "Oklahoma",
	"Oklahoma St Cowboys": "Oklahoma State",
	"Oklahoma State Cowboys": "Oklahoma State",
	"Old Dominion Monarchs": "Old Dominion",
	"Ole Miss Rebels": "Ole Miss",
	"Omaha Mavericks": "Nebraska Omaha",
	"Oral Roberts Golden Eagles": "Oral Roberts",
	"Oregon Ducks": "Oregon",
	"Oregon St Beavers": "Oregon State",
	"Oregon State Beavers": "Oregon State",
	"Pacific Tigers": "Pacific",
	"Penn State Nittany Lions": "Penn State",
	"Pepperdine Waves": "Pepperdine",
	"Pittsburgh Panthers": "Pittsburgh",
	"Portland Pilots": "Portland",
	"Portland St Vikings": "Portland State",
	"Prairie View Panthers": "Prairie View A&M",
	"Providence Friars": "Providence",
	"Purdue Boilermakers": "Purdue",
	"Queens University Royals": "Queens",
	"Quinnipiac Bobcats": "Quinnipiac",
	"Rhode Island Rams": "Rhode Island",
	"Rice Owls": "Rice",
	"Richmond Spiders": "Richmond",
	"Rider Broncs": "Rider",
	"Rutgers Scarlet Knights": "Rutgers",
	"SE Louisiana Lions": "SE Louisiana",
	"SE Missouri St Redhawks": "SEMO",
	"SMU Mustangs": "SMU",
	"Sacramento St Hornets": "Sacramento State",
	"Sacred Heart Pioneers": "Sacred Heart",
	"Saint Joseph's Hawks": "Saint Joseph's",
	"Saint Louis Billikens": "Saint Louis",
	"Saint Mary's Gaels": "Saint Mary's",
	"Saint Peter's Peacocks": "Saint Peter's",
	"Sam Houston St Bearkats": "Sam Houston State",
	"Sam Houston State Bearkats": "Sam Houston State",
	"Samford Bulldogs": "Samford",
	"San Diego St Aztecs": "San Diego State",
	"San Diego State Aztecs": "San Diego State",
	"San Diego Toreros": "San Diego",
	"San Francisco Dons": "San Francisco",
	"San Jose State Spartans": "San Jose State",
	"San José St Spartans": "San Jose State",
	"Santa Clara Broncos": "Santa Clara",
	"Seton Hall Pirates": "Seton Hall",
	"South Alabama Jaguars": "South Alabama",
	"South Carolina Gamecocks": "South Carolina",
	"South Carolina St Bulldogs": "South Carolina State",
	"South Carolina Upstate Spartans": "South Carolina Upstate",
	"South Dakota Coyotes": "South Dakota",
	"South Dakota St Jackrabbits": "South Dakota State",
	"South Florida Bulls": "South Florida",
	"Southern Illinois Salukis": "Southern Illinois",
	"Southern Indiana Screaming Eagles": "Southern Indiana",
	"Southern Jaguars": "Southern University",
	"Southern Miss Golden Eagles": "Southern Miss",
	"Southern Mississippi Golden Eagles": "Southern Miss",
	"Southern Utah Thunderbirds": "Southern Utah",
	"St. Bonaventure Bonnies": "St. Bonaventure",
	"St. Francis (PA) Red Flash": "Saint Francis PA",
	"St. John's Red Storm": "St John's",
	"St. Thomas (MN) Tommies": "St. Thomas",
	"Stanford Cardinal": "Stanford",
	"Stephen F. Austin Lumberjacks": "Stephen F Austin",
	"Stetson Hatters": "Stetson",
	"Stonehill Skyhawks": "Stonehill",
	"Stony Brook Seawolves": "Stony Brook",
	"Syracuse Orange": "Syracuse",
	"TCU Horned Frogs": "TCU",
	"Tarleton State Texans": "Tarleton",
	"Temple Owls": "Temple",
	"Tenn-Martin Skyhawks": "UT Martin",
	"Tennessee Tech Golden Eagles": "Tennessee Tech",
	"Tennessee Volunteers": "Tennessee",
	"Texas A&M Aggies": "Texas A&M",
	"Texas A&M-Commerce Lions": "Texas A&M Commerce",
	"Texas Longhorns": "Texas",
	"Texas State Bobcats": "Texas State",
	"Texas Tech Red Raiders": "Texas Tech",
	"The Citadel Bulldogs": "Citadel",
	"Toledo Rockets": "Toledo",
	"Towson Tigers": "Towson",
	"Troy Trojans": "Troy",
	"Tulane Green Wave": "Tulane",
	"Tulsa Golden Hurricane": "Tulsa",
	"UAB Blazers": "UAB",
	"UC Irvine Anteaters": "UC Irvine",
	"UC Riverside Highlanders": "UC Riverside",
	"UC San Diego Tritons": "San Diego Tritons",
	"UC Santa Barbara Gauchos": "UC Santa Barbara",
	"UCF Knights": "Central Florida",
	"UCLA Bruins": "UCLA",
	"UConn Huskies": "Connecticut",
	"UIC Flames": "UIC",
	"UL Monroe Warhawks": "UL Monroe",
	"UMKC Kangaroos": "Kansas City",
	"UMass Lowell River Hawks": "UMass Lowell",
	"UMass Minutemen": "Massachusetts",
	"UNC Greensboro Spartans": "UNC Greensboro",
	"UNC Wilmington Seahawks": "UNC Wilmington",
	"UNLV Rebels": "UNLV",
	"USC Trojans": "USC",
	"UT Rio Grande Valley Vaqueros": "UT Rio Grande Valley",
	"UTEP Miners": "UTEP",
	"UTSA Roadrunners": "UTSA",
	"Utah State Aggies": "Utah State",
	"Utah Tech Trailblazers": "Utah Tech",
	"Utah Utes": "Utah",
	"VCU Rams": "VCU",
	"Valparaiso Beacons": "Valparaiso",
	"Vanderbilt Commodores": "Vanderbilt",
	"Vermont Catamounts": "Vermont",
	"Villanova Wildcats": "Villanova",
	"Virginia Cavaliers": "Virginia",
	"Virginia Tech Hokies": "Virginia Tech",
	"Wagner Seahawks": "Wagner",
	"Wake Forest Demon Deacons": "Wake Forest",
	"Washington Huskies": "Washington",
	"Washington St Cougars": "Washington State",
	"Washington State Cougars": "Washington State",
	"West Virginia Mountaineers": "WV Mountaineers",
	"Western Carolina Catamounts": "Western Carolina",
	"Western Illinois Leathernecks": "Western Illinois",
	"Western Kentucky Hilltoppers": "Western Kentucky",
	"Western Michigan Broncos": "Western Michigan",
	"Wichita St Shockers": "Wichita State",
	"William & Mary Tribe": "William & Mary",
	"William and Mary Tribe": "William & Mary",
	"Winthrop Eagles": "Winthrop",
	"Wisconsin Badgers": "Wisconsin",
	"Wofford Terriers": "Wofford",
	"Wright St Raiders": "Wright State",
	"Wyoming Cowboys": "Wyoming",
	"Xavier Musketeers": "Xavier",
	"Youngstown St Penguins": "Youngstown State",
	"Columbia Lions":"Columbia",
	"Brown Bears":"Brown",
	"Iona Gaels":"Iona",
	"VMI Keydets":"VMI",
	"UMBC Retrievers":"UMBC",
	"Cornell Big Red":"Cornell",
	"Yale Bulldogs":"Yale",
	"Dartmouth Big Green":"Dartmouth",
	"Harvard Crimson":"Harvard",
	"Fairfield Stags":"Fairfield",
	"Robert Morris Colonials":"Robert Morris",
	"Texas A&M Commerce":"Texas A&M Commerce",
	"North Dakota Fighting Hawks":"North Dakota",
	"Chicago St Cougars":"Chicago State",
	"Le Moyne Dolphins":"Le Moyne",
	"UT-Arlington Mavericks":"UT Arlington",
	"Morehead St Eagles":"Morehead State",
	"Utah Valley Wolverines":"Utah Valley State",
	"Evansville Purple Aces":"Evansville",
	"Texas Southern Tigers":"Texas Southern",
	"UNC Asheville Bulldogs":"UNC Asheville",
	"Presbyterian Blue Hose":"Presbyterian",
	"Radford Highlanders":"Radford",
	"Tennessee St Tigers":"Tennessee State",
	"Colgate Raiders":"Colgate",
	"Texas A&M-CC Islanders":"Texas A&M-CC",
	"Pennsylvania Quakers":"Penn",
	"Princeton Tigers":"Princeton",
	"Seattle Redhawks":"Seattle",
	"Miss Valley St Delta Devils":"Miss Valley State",
	"Lehigh Mountain Hawks":"Lehigh",
	"Lamar Cardinals":"Lamar",
	"Marist Red Foxes":"Marist",
	"Siena Saints":"Siena",
	"Manhattan Jaspers":"Manhattan",
	"Idaho State Bengals":"Idaho State",
	"SIU-Edwardsville Cougars":"SIU Edwardsville",
	"Weber State Wildcats":"Weber State",
	"UC Davis Aggies":"UC Davis",


}


